Update for tomlkit 0.8.0
In this version the elements of "body" are automatically manipulated
behind the scenes when an entry is removed.

This fixes a build error in CircuitPython:
```
  File "gen_stage2.py", line 15, in main
    flashes = cascadetoml.filter_toml(pathlib.Path("../../data/nvm.toml"), skus)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/cascadetoml.py", line 182, in filter_toml
    del output_doc[object_type].body[i]
IndexError: list assignment index out of range
```